# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"
  stripe:
    image: stripe/stripe-cli:latest
    environment:
      STRIPE_API_KEY: sk_test_qNFI4mD2kNWlhYxNRSmN3VSZ
      STRIPE_DEVICE_NAME: integration-tests
    command: "listen --forward-to http://server:3333/webhooks/stripe"
