name: Trigger auto deployment for server-subgraph

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/server-subgraph-AutoDeployTrigger-face39a3-ade5-4f71-9530-bd02bfff878e.yml'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca3901f1871aacr.azurecr.io
          username: ${{ secrets.SERVERSUBGRAPH_REGISTRY_USERNAME }}
          password: ${{ secrets.SERVERSUBGRAPH_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca3901f1871aacr.azurecr.io/server-subgraph:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVERSUBGRAPH_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n server-subgraph -g graph-federation --server ca3901f1871aacr.azurecr.io --username  ${{ secrets.SERVERSUBGRAPH_REGISTRY_USERNAME }} --password ${{ secrets.SERVERSUBGRAPH_REGISTRY_PASSWORD }}
            az containerapp update -n server-subgraph -g graph-federation --image ca3901f1871aacr.azurecr.io/server-subgraph:${{ github.sha }} --replace-env-vars DATABASE_URL=postgres://${AZURE_POSTGRESQL_USER}:${AZURE_POSTGRESQL_PASSWORD}@${AZURE_POSTGRESQL_HOST}/${AZURE_POSTGRESQL_DATABASE}?sslmode=require&connection_limit=15&pool_timeout=30
